/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_IOTADOORLOCK_ACCESSSTATUS_PB_H_INCLUDED
#define PB_IOTADOORLOCK_ACCESSSTATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _iotaDoorLock_AccessStatus_Code {
    iotaDoorLock_AccessStatus_Code_STATUS_GRANTED = 1,
    iotaDoorLock_AccessStatus_Code_STATUS_DENIED = 2,
    iotaDoorLock_AccessStatus_Code_STATUS_ERROR = 3,
    iotaDoorLock_AccessStatus_Code_STATUS_NO_CONNECTION_TO_GATEWAY = 6
} iotaDoorLock_AccessStatus_Code;
#define _iotaDoorLock_AccessStatus_Code_MIN iotaDoorLock_AccessStatus_Code_STATUS_GRANTED
#define _iotaDoorLock_AccessStatus_Code_MAX iotaDoorLock_AccessStatus_Code_STATUS_NO_CONNECTION_TO_GATEWAY
#define _iotaDoorLock_AccessStatus_Code_ARRAYSIZE ((iotaDoorLock_AccessStatus_Code)(iotaDoorLock_AccessStatus_Code_STATUS_NO_CONNECTION_TO_GATEWAY+1))

/* Struct definitions */
typedef struct _iotaDoorLock_AccessStatus {
    iotaDoorLock_AccessStatus_Code status_code;
/* @@protoc_insertion_point(struct:iotaDoorLock_AccessStatus) */
} iotaDoorLock_AccessStatus;


/* Initializer values for message structs */
#define iotaDoorLock_AccessStatus_init_default   {_iotaDoorLock_AccessStatus_Code_MIN}
#define iotaDoorLock_AccessStatus_init_zero      {_iotaDoorLock_AccessStatus_Code_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define iotaDoorLock_AccessStatus_status_code_tag 1

/* Struct field encoding specification for nanopb */
#define iotaDoorLock_AccessStatus_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UENUM, status_code, 1)
#define iotaDoorLock_AccessStatus_CALLBACK NULL
#define iotaDoorLock_AccessStatus_DEFAULT NULL

extern const pb_msgdesc_t iotaDoorLock_AccessStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iotaDoorLock_AccessStatus_fields &iotaDoorLock_AccessStatus_msg

/* Maximum encoded size of messages (where known) */
#define iotaDoorLock_AccessStatus_size           2

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
