/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_IOTADOORLOCK_DIDREQUEST_PB_H_INCLUDED
#define PB_IOTADOORLOCK_DIDREQUEST_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _iotaDoorLock_DIDRequest {
    pb_callback_t schema;
    pb_callback_t method;
    pb_callback_t id;
/* @@protoc_insertion_point(struct:iotaDoorLock_DIDRequest) */
} iotaDoorLock_DIDRequest;


/* Initializer values for message structs */
#define iotaDoorLock_DIDRequest_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define iotaDoorLock_DIDRequest_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define iotaDoorLock_DIDRequest_schema_tag       1
#define iotaDoorLock_DIDRequest_method_tag       2
#define iotaDoorLock_DIDRequest_id_tag           3

/* Struct field encoding specification for nanopb */
#define iotaDoorLock_DIDRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING, schema, 1) \
X(a, CALLBACK, REQUIRED, STRING, method, 2) \
X(a, CALLBACK, REQUIRED, STRING, id, 3)
#define iotaDoorLock_DIDRequest_CALLBACK pb_default_field_callback
#define iotaDoorLock_DIDRequest_DEFAULT NULL

extern const pb_msgdesc_t iotaDoorLock_DIDRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iotaDoorLock_DIDRequest_fields &iotaDoorLock_DIDRequest_msg

/* Maximum encoded size of messages (where known) */
/* iotaDoorLock_DIDRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
