/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_IOTADOORLOCK_DIDRESPONSE_PB_H_INCLUDED
#define PB_IOTADOORLOCK_DIDRESPONSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _iotaDoorLock_DIDResponse_Code {
    iotaDoorLock_DIDResponse_Code_SUCCESSFUL_SENT = 1,
    iotaDoorLock_DIDResponse_Code_SEND_ERROR = 2,
    iotaDoorLock_DIDResponse_Code_NO_CONNECTION_TO_GATEWAY = 3
} iotaDoorLock_DIDResponse_Code;
#define _iotaDoorLock_DIDResponse_Code_MIN iotaDoorLock_DIDResponse_Code_SUCCESSFUL_SENT
#define _iotaDoorLock_DIDResponse_Code_MAX iotaDoorLock_DIDResponse_Code_NO_CONNECTION_TO_GATEWAY
#define _iotaDoorLock_DIDResponse_Code_ARRAYSIZE ((iotaDoorLock_DIDResponse_Code)(iotaDoorLock_DIDResponse_Code_NO_CONNECTION_TO_GATEWAY+1))

/* Struct definitions */
typedef struct _iotaDoorLock_DIDResponse {
    iotaDoorLock_DIDResponse_Code code;
/* @@protoc_insertion_point(struct:iotaDoorLock_DIDResponse) */
} iotaDoorLock_DIDResponse;


/* Initializer values for message structs */
#define iotaDoorLock_DIDResponse_init_default    {_iotaDoorLock_DIDResponse_Code_MIN}
#define iotaDoorLock_DIDResponse_init_zero       {_iotaDoorLock_DIDResponse_Code_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define iotaDoorLock_DIDResponse_code_tag        1

/* Struct field encoding specification for nanopb */
#define iotaDoorLock_DIDResponse_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UENUM, code, 1)
#define iotaDoorLock_DIDResponse_CALLBACK NULL
#define iotaDoorLock_DIDResponse_DEFAULT NULL

extern const pb_msgdesc_t iotaDoorLock_DIDResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iotaDoorLock_DIDResponse_fields &iotaDoorLock_DIDResponse_msg

/* Maximum encoded size of messages (where known) */
#define iotaDoorLock_DIDResponse_size            2

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
