/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_IOTADOORLOCK_ERRORRESPONSE_PB_H_INCLUDED
#define PB_IOTADOORLOCK_ERRORRESPONSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _iotaDoorLock_ErrorResponse {
    pb_callback_t message;
    uint32_t time;
/* @@protoc_insertion_point(struct:iotaDoorLock_ErrorResponse) */
} iotaDoorLock_ErrorResponse;


/* Initializer values for message structs */
#define iotaDoorLock_ErrorResponse_init_default  {{{NULL}, NULL}, 0}
#define iotaDoorLock_ErrorResponse_init_zero     {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define iotaDoorLock_ErrorResponse_message_tag   1
#define iotaDoorLock_ErrorResponse_time_tag      2

/* Struct field encoding specification for nanopb */
#define iotaDoorLock_ErrorResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING, message, 1) \
X(a, STATIC, REQUIRED, UINT32, time, 2)
#define iotaDoorLock_ErrorResponse_CALLBACK pb_default_field_callback
#define iotaDoorLock_ErrorResponse_DEFAULT NULL

extern const pb_msgdesc_t iotaDoorLock_ErrorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iotaDoorLock_ErrorResponse_fields &iotaDoorLock_ErrorResponse_msg

/* Maximum encoded size of messages (where known) */
/* iotaDoorLock_ErrorResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
